// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Turquoise.Administration.Infrastructure.SQL;

namespace Turquoise.Administration.Infrastructure.SQL.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20210211185747_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasPostgresExtension("uuid-ossp")
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.Administrator.Administrator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("CreationAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("name");

                    b.Property<Guid?>("RowGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_guid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("surname");

                    b.HasKey("Id");

                    b.ToTable("administrator", "user");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.Administrator.AdministratorPassword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<Guid?>("RowGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_guid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("salt");

                    b.HasKey("Id");

                    b.ToTable("administrator_password", "user");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.Branch.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("code");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("name");

                    b.Property<Guid?>("RowGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_guid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.ToTable("branch", "user");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.ChoiceGroup.Choice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChoiceGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("choice_group_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(6)")
                        .HasColumnName("color");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Description")
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("name");

                    b.Property<long>("Number")
                        .HasColumnType("bigint")
                        .HasColumnName("number");

                    b.Property<Guid?>("RowGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_guid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.HasIndex("ChoiceGroupId");

                    b.ToTable("choice", "survey");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.ChoiceGroup.ChoiceGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("code");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("name");

                    b.Property<Guid?>("RowGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_guid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.ToTable("choice_group", "survey");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.Doctor.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("CreationAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("name");

                    b.Property<Guid?>("RowGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_guid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("surname");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("doctor", "user");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.Survey.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("body");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("ChoiceGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("choice_group_id");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("CreationAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_at")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("image");

                    b.Property<Guid?>("RowGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_guid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ChoiceGroupId");

                    b.ToTable("survey", "survey");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.Survey.SurveyBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("RowGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_guid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_id");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("SurveyId");

                    b.ToTable("survey_branch", "survey");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.SurveyAnswer.SurveyAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("CreationAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("RowGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_guid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.ToTable("survey_answer", "survey");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.SurveyAnswer.SurveyAnswerChoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("choice_id");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Corrdinates")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("coordinates");

                    b.Property<byte>("DrawingType")
                        .HasColumnType("smallint")
                        .HasColumnName("drawing_type");

                    b.Property<Guid?>("RowGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_guid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("SurveyAnswerId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_answer_id");

                    b.HasKey("Id");

                    b.HasIndex("ChoiceId");

                    b.HasIndex("SurveyAnswerId");

                    b.ToTable("survey_answer_choice", "survey");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.Administrator.AdministratorPassword", b =>
                {
                    b.HasOne("Turquoise.Administration.Domain.Aggregation.Administrator.Administrator", "Administrator")
                        .WithOne("Password")
                        .HasForeignKey("Turquoise.Administration.Domain.Aggregation.Administrator.AdministratorPassword", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.ChoiceGroup.Choice", b =>
                {
                    b.HasOne("Turquoise.Administration.Domain.Aggregation.ChoiceGroup.ChoiceGroup", "ChoiceGroup")
                        .WithMany("Choices")
                        .HasForeignKey("ChoiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChoiceGroup");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.Doctor.Doctor", b =>
                {
                    b.HasOne("Turquoise.Administration.Domain.Aggregation.Branch.Branch", "Branch")
                        .WithMany("Doctors")
                        .HasForeignKey("BranchId");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.Survey.Survey", b =>
                {
                    b.HasOne("Turquoise.Administration.Domain.Aggregation.Branch.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("Turquoise.Administration.Domain.Aggregation.ChoiceGroup.ChoiceGroup", "ChoiceGroup")
                        .WithMany()
                        .HasForeignKey("ChoiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("ChoiceGroup");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.Survey.SurveyBranch", b =>
                {
                    b.HasOne("Turquoise.Administration.Domain.Aggregation.Branch.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turquoise.Administration.Domain.Aggregation.Survey.Survey", "Survey")
                        .WithMany("SurveyBranches")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.SurveyAnswer.SurveyAnswerChoice", b =>
                {
                    b.HasOne("Turquoise.Administration.Domain.Aggregation.ChoiceGroup.Choice", "Choice")
                        .WithMany()
                        .HasForeignKey("ChoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turquoise.Administration.Domain.Aggregation.SurveyAnswer.SurveyAnswer", "SurveyAnswer")
                        .WithMany("AnswerChoices")
                        .HasForeignKey("SurveyAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Choice");

                    b.Navigation("SurveyAnswer");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.Administrator.Administrator", b =>
                {
                    b.Navigation("Password");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.Branch.Branch", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.ChoiceGroup.ChoiceGroup", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.Survey.Survey", b =>
                {
                    b.Navigation("SurveyBranches");
                });

            modelBuilder.Entity("Turquoise.Administration.Domain.Aggregation.SurveyAnswer.SurveyAnswer", b =>
                {
                    b.Navigation("AnswerChoices");
                });
#pragma warning restore 612, 618
        }
    }
}
